sudo: required

language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -f ./docker-web/Dockerfile -t pkap/gbridge-web .
  - docker build -f ./docker-redis-worker/Dockerfile -t pkap/gbridge-redis-worker .
  - docker build -f ./docker-web-nginx/Dockerfile -t pkap/gbridge-web-nginx .
  - docker build -f ./docker-web-fpm/Dockerfile -t pkap/gbridge-web-fpm .
  - docker push pkap/gbridge-web
  - docker push pkap/gbridge-redis-worker
  - docker push pkap/gbridge-web-nginx
  - docker push pkap/gbridge-web-fpm
