version: '3'
networks:
  backend:
    driver: bridge
  web_frontend:
    driver: bridge

services:
  database:
    image: mysql:5
    #volumes:
    #  - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: gbridge_db
      MYSQL_USER: gbridge_db
      MYSQL_PASSWORD: abc132cba
    #expose, rather than ports, only allows connections from linked machines
    expose:
      - "3306"
    networks:
      - backend
  cache:
    image: redis:4
    restart: always
    expose:
      - "6379"
    networks:
      - backend
  web:
    image: pkap/gbridge-web-nginx:latest
    restart: always
    ports:
     - "80:8880"
    environment: &webapp-environment
      - APP_ENV=local
      - APP_KEY=base64:yBHt9LN/MRQqPiub6ECiPl+eWrJTbjXWjTnQM3F9x4k=
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - APP_URL=http://localhost

      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=gbridge_db
      - DB_USERNAME=gbridge_db
      - DB_PASSWORD=abc132cba

      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - QUEUE_DRIVER=sync

      - REDIS_HOST=cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null

      - GOOGLE_CLIENTID=${GBRIDGE_GOOGLE_CLIENTID}
      - GOOGLE_PROJECTID=${GBRIDGE_GOOGLE_PROJECTID}
    links:
      - database
      - cache
      - web-fpm
    depends_on: 
      - database
      - cache
      - web-fpm
    networks:
      - web_frontend
      - backend
    volumes:
      - websrc:/var/www
  web-fpm:
    image: pkap/gbridge-web-fpm:latest
    restart: always
    networks:
      - backend
    volumes:
      - websrc:/var/www
    environment: *webapp-environment
  redis-worker:
    image: pkap/gbridge-redis-worker:latest
    restart: always
    environment:
      - GBRIDGE_REDISWORKER_REDIS=redis://cache:6379
      - GBRIDGE_REDISWORKER_MQTT=mqtt://${GBRIDGE_MQTT_CONNECTION}
      - GBRIDGE_REDISWORKER_HOMEGRAPHKEY=${GBRIDGE_GOOGLE_HOMEGRAPHKEY}
    networks:
      - backend
    links:
      - cache
    depends_on:
      - cache
volumes:
  websrc:
