version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker-web/Dockerfile
    ports:
     - "80:80"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:yBHt9LN/MRQqPiub6ECiPl+eWrJTbjXWjTnQM3F9x4k=
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - APP_URL=http://localhost

      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret

      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - QUEUE_DRIVER=sync

      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null

      - GOOGLE_CLIENTID=abc123
      - GOOGLE_PROJECTID=kappelt-smarthome-eb8cd
  redis-worker:
    build:
      context: ./
      dockerfile: ./docker-redis-worker/Dockerfile
    environment:
      - GBRIDGE_REDISWORKER_REDIS=redis://192.168.2.174:6379
      - GBRIDGE_REDISWORKER_MQTT=mqtt://hcpi01.int.kappelt.net:1883
      - GBRIDGE_REDISWORKER_HOMEGRAPHKEY=abc123